# Config file for genqlient to generate GraphQL queries (in a Go file).
# See `go doc github.com/Khan/genqlient/generate.Config` for documentation.

schema: schema.graphql

operations:
- queries.graphql

generated: generated-queries.go

# needed since it doesn't match the directory name:
package: main

# We bind github's DateTime scalar type to Go's time.Time (which conveniently
# already defines MarshalJSON and UnmarshalJSON).  This means genqlient will
# use time.Time when a query requests a DateTime, and is required for custom
# scalars.
bindings:
  BigInt:
    type: int
  Bytes:
    type: "[]byte"
